### ISSUE TITLE
Primeiro Meetup

### ISSUE THREAD

**Issue by danilovaz** [beerjs/sjc#1]
Fala galera! Vamos usar essa issue para discutir a respeito do primeiro meetup beer.js em São José dos Campos :smile: 

Lembrando que o pessoal da região também é muito bem-vindo.

Para organizar melhor essa issue, envie sua sugestão para o próximo meetup nesse formato:
## Beer.js no [Nome do Bar com link do site/facebook/twitter se tiver]
- Data e Hora (ex. 26/02 às 19h)
- Assuntos a serem abordados (ex. node.js e io.js)
- Algum comentário que ache relevante

Conto com a ajuda de vocês, obrigado :+1: :smiley:

**Comment by marciomoradei** [comment]
## Beer.js no [Coronel](http://www.facebook.com/bardocoronel)
- Data e hora: 21/02 às 20h00
- Assuntos a serem abordados: node.js/ember.js
- Comentário: Pouco blablabla e muita beer.js

**Comment by cassiocardoso** [comment]
Coronel :+1: 

Mas seria bom ter um tempo maior pra galera poder se planejar né? :smile:

**Comment by evansantos** [comment]
Coronel +1

**Comment by danilovaz** [comment]
@cassiocardoso sim, pra esse fds não dá não rs!

**Comment by danilovaz** [comment]
## Beer.js no [Coronel](http://www.facebook.com/bardocoronel)
- Data e hora: 13/03 às 18h30
- Assuntos a serem abordados: Utilizar AgularJS ou Facebook React?
- Comentário: pelo local ser "aberto" não recomendo levarem notebooks e tal, por isso acho que os assuntos abordados devam ser mais de cunho para uma discussão :smile: nos próximos, mais bem planejados e tal pode até ser que dê pra levar notebooks e colocar em prática as discussões

**Comment by evansantos** [comment]
## Beer.js no [Emporio Hopfields](https://www.facebook.com/EmporioHopfields)
- Data e hora: 12/03 às 18h30
- Assuntos a serem abordados: Utilizar AgularJS, MEAN?

**Comment by Arlen2014** [comment]
Um bom lugar para se reunir seria no DUE BAR (https://www.facebook.com/pages/DUE-Bar-e-Bistr%C3%B4/551633648208794?ref=ts&fref=ts), la tem wireless e mesa para ligar os Notebooks, alem de cervejas e chopps artesanais e importados.

**Comment by danilovaz** [comment]
Pessoal, peço desculpas pelo tempo ausente!

Mas agora vamos voltar com tudo =)

Tenho agora a ajuda do @fbsobral na organização, por ora, estamos melhorando a estrutura para fazer um primeiro meetup bem massa.

Estarei fechando essa issue para manter a organização. 

O local do meetup nós decidimos por enquanto, deixar fechado para nossa escolha. Já que ainda somos um grupo de Beer.JS pequeno, essa seria a melhor maneira de manter as coisas em ordem.

Criarei uma issue para que todos nós possamos decidir os assuntos do primeiro meetup que deve acontecer dentro de 1 mês.

Conto com a colaboração de vocês. Valeu galera =)

**Comment by danilovaz** [comment]
Pessoal, peço desculpas pelo tempo ausente!

Mas agora vamos voltar com tudo =)

Tenho agora a ajuda do @fbsobral na organização, por ora, estamos melhorando a estrutura para fazer um primeiro meetup bem massa.

Estarei fechando essa issue para manter a organização.

O local do meetup nós decidimos por enquanto, deixar fechado para nossa escolha. Já que ainda somos um grupo de Beer.JS pequeno, essa seria a melhor maneira de manter as coisas em ordem.

Criarei uma issue para que todos nós possamos decidir os assuntos do primeiro meetup que deve acontecer dentro de 1 mês.

Conto com a colaboração de vocês. Valeu galera =)
