### ISSUE TITLE
Assuntos Primeiro Meetup

### ISSUE THREAD

**Issue by danilovaz** [beerjs/sjc#4]
Abrirei essa issue para sugestões de assuntos a serem abordados no meetup. Lembrando que pode ser assuntos que você tenha conhecimento ou assunto que esteja adquirir o conhecimento.

O bacana é ter alguém com algum background no assunto para que possa dar uma introdução aos demais na conversa =)

Para não floodar essa issue, envie apenas o/os assuntos que gostaria que fossem abordados no primeiro meetup. Uma dica, não dê sugestão de assuntos que não se complementam...no máximo pode ser algo do tipo emberJS vs angularJS (por exemplo), que nesse caso é um debate interessante de ideias.
- MEAN (MongoDB, Express, AngularJS e NodeJS)

C/C @fbsobral

**Comment by rodrigoagostin** [comment]
Angularjs 1.X e/ou Angularjs 2.0

**Comment by pedro-hos** [comment]
AngularJS vs. Backbone.js vs. Ember.js (sugestão, não manjo dos paranauê)

**Comment by rodrigoagostin** [comment]
Vou colocar um assunto que está sendo bastante discutido no Quora
- Reactjs vs Angularjs

**Comment by rodrigoagostin** [comment]
*Quora

Em 25 de agosto de 2015 14:33, Rodrigo Agostinho <
therodrigoagostin@gmail.com> escreveu:

> Vou colocar um assunto que está sendo bastante discutido no Quota
>
>  - Reactjs vs Angularjs
>

**Comment by tiarebalbi** [comment]
Bom tópico

**Comment by pedro-hos** [comment]
+1 
- Reactjs vs Angularjs

@rodrigoagostin

**Comment by danilovaz** [comment]
Estivemos parados com a organização do BeerJS. Mas agora vamos voltar com tudo :+1: 

Para começar (novamente) certo, vou fechar essa issue. Mais novidades colocaremos aqui, no Meetup e no Twitter. Em breve novidades pro primeiro encontro.

Valeu a paciência e tamojunto :smile:
